hyperjumptech/monika-config-generator

.github/workflows/deploy.yml

This PR disables deployment on PR

ci: disable deployment on PR

---

CODE_OF_CONDUCTS.md
LICENSE.txt
README.md

This PR updates the README with more information.

chore: update README.md

---

components/button/index.tsx
components/index.tsx
components/textInput/index.tsx
pages/web-form.tsx

This PR implements issue #5 
- run `npm run dev`
- open [http://localhost:3000/web-form](http://localhost:3000/web-form)

Create web form entry

---

components/radio/index.tsx
next.config.js
pages/index.tsx
pages/what-do-you-want.tsx

Create What Do You Want to monitor page. Resolves #3 
1. Run npm run dev
2. Open localhost:3000 in browser
3. Choose `i'm new to monika`
4. click next

feat: what do you want to monitor page

---

pages/web-page.tsx

feat: adds web page

---

contexts/NotificationContext.tsx
contexts/NotificationContextInterface.ts
contexts/ProbeContext.tsx
contexts/ProbeContextInterface.ts
contexts/importer.ts
pages/index.tsx

feat: import existing config json file

---

components/button/index.tsx
components/form/index.tsx
components/form/item.tsx
components/index.tsx
components/textInput/index.tsx
hooks/use-form/index.ts
pages/notifications.tsx

Create notification entry form. Resolves #7 
1. Run `npm run dev`
2. Open localhost:3000 in browser

Feat: Create Notification Entry Form

---

components/index.tsx
components/notifcard/index.tsx
components/select/index.tsx
components/sidebar/index.tsx
contexts/NotificationContext.tsx
contexts/NotificationContextInterface.ts
pages/advanced.tsx
utils/notificationForms.ts

feat: create notifications form

---

pages/index.tsx

this PR closes issue #16 
- redirect to `/advanced` page after importing json file

feat: redirect to /advanced page after importing config file

---

components/generate-config-modal/index.tsx
components/notif-card/index.tsx
contexts/notification-context.tsx
utils/notification-forms.ts

feat: collects config data from context

---

pages/api-entry.tsx
pages/web-form.tsx
pages/web-page.tsx
pages/what-do-you-want.tsx

feat: add action for next buttons

---

utils/notification-forms.ts

This PR updates default SMTP port from `0` to `587`

refactor: update default smtp port

---

components/select/index.tsx

Fix Margin in Select Input

---

components/generate-config-modal/index.tsx
pages/download.tsx
utils/download-json-config.ts

fixing issue #46 by creating helper function to download json config file then use it in advanced page and download page.
the downloaded file (monika.json ) will not have right content because #38 is still not done

fix: Bug in Download page

---

pages/index.tsx

fix: navigate to /advanced when select 'I have used Monika before'

---

pages/api-entry.tsx
pages/web-form.tsx
pages/web-page.tsx

fix: should show notification entry page before download page

---

components/probe-card/index.tsx
components/probe-request-form/index.tsx
components/probe-response-time/index.tsx
contexts/importer.ts
pages/index.tsx

implement issue #53 by:
- fix: error, probe name & desc, and default check alerts
- show error if file not valid (default file is json file. user cannot upload other than json file, so the validation is just checking is the file have probes and notifications key)
For more advanced validation in the future, we can use `validateConfig` function from monika, but for now it cannot be used.

fix: Cannot import existing configuration 

---

components/head-page/index.tsx
components/index.tsx
pages/advanced.tsx
pages/api-entry.tsx
pages/download.tsx
pages/index.tsx
pages/notifications.tsx
pages/web-form.tsx
pages/web-page.tsx
pages/what-do-you-want.tsx

Implement issue #69 
1. run localhost:3000
2. visit every page, see the title in tab browser or in developer console elements

feat: Add title for all the pages

---

.github/workflows/test.yml

This PR adds a test step in the Test workflow.

chore: run tests in github workflow

---

components/notif-card/index.tsx
contexts/notification-context.tsx
package-lock.json
package.json
pages/notifications.tsx
utils/notification-forms.ts

This PR fixes #77 
This PR adds an option for Desktop notifications
Try to create a config using all options available in the wizard, and add desktop notifications as the notification channel

Add Desktop Notification Options

---

components/probe-alert-form/index.tsx
components/probe-alert-form/probe-alert-form.test.tsx
contexts/probe-context.tsx
package-lock.json
package.json

Remove subject field. Resolve #94.
- Remove subject field
- Update monika
1. Run `npm run dev`
2. Open `http://localhost:3000`
3. Choose `I have used Monika before` and click `Next`
4. Fill the form and click `Generate Config File`
5. Click `Download file`

fix: remove subject field

---

pages/web-page.tsx

Add required validation. Resolve #103.
Add HTML required attribute.
1. Run `npm run dev`
2. Open http://localhost:3000` on your browser
3. Select `I'm new to Monika` and Click `Next`
4. Click `A web page`
5. Click `Next`

feat: add required validation

---

contexts/importer.ts
pages/api-entry.tsx
pages/web-form.tsx
pages/web-page.tsx

This PR fixes #104 
This PR sets the default probe name if there is no probe name
1. Create a config by selecting I'm New to Monika -> A web page
2. Create a config by selecting I'm New to Monika -> A web form
3. Create a config by selecting I'm New to Monika -> API server
4. Create a config by selecting I have a configuration file

Feat: Set default names for probes

---

pages/index.tsx

Add information about using vscode and YAML extension (#112)
